### PR TITLE
Jneb formulas

### PR DESCRIPTION
**Pull request by jneb**
Hi folks, just saw the 0.8 version of y-cruncher.
As a fan, I contribute three constants:
- i^i : the famous "surprise real number"
- exp(Pi) : creatively constructed from hypergeom series
- Sqrt(2) : using a faster convergent series than the standard

Hope you like one or more of these.
Jurjen

### CODE REVIEW

**Comment by Mysticial** [comment]
Oh wow, this is interesting! I didn't know such a hypergeometric series existed for Cos/Sinh(pi).

Is there a reference I can read more about it? Or is this entirely new research?

**Comment by jneb** [comment]
Glad you like them!

There are lots of interesting formulas that can be found in standard works on hypergeometric functions. Unfortunately, only a few are really
interesting, but some are extremely weird, containing things like G+pi+ln(2) and other strange stuff.

A great resource is https://dlmf.nist.gov/15
There are also references to standard works in there.

But I also just played trying out values for the parameters and asking Wolfram alpha to simplify.
I found these among others:

2F1(i/2,-i/2,½,x^2)=cosh(arcsin(x))
2F1(½+i/2,½-i/2,3/2,x^2)=sinh(arcsin(x))/x
2F1(i,-i,½,-x^2)=cos(2*arcsinh(x))
2F1(i/2,-i/2,½,-x^2)=cos(arcsinh(x))
2F1(½+i/2,½-i/2,3/2,-x^2)=sin(arcsinh(x))/x

And the formulas i used for sinh(pi) and cosh(pi) follow trivially.

(Edited for clarity)

**Comment by jzhansen** [comment]
Jurjen, I liked these formulae. Thanks a lot for sharing them.

Jorge

**Comment by Mysticial** [comment]
Is the series related to this?

https://math.stackexchange.com/questions/1604718/rational-series-representation-of-e-pi

**Comment by jneb** [comment]
To be honest, I don't know much about asymptotics, but it looks like the same series to me.

**Comment by jneb** [comment]
You may want to update the FAQ, as exp(pi) is explicitly mentioned there!

**Comment by jneb** [comment]
Here's a validation file for a 100m computation I did. Maybe useful for your checks.
[i^i - 20230904-144446.txt](https://github.com/Mysticial/y-cruncher-Formulas/files/12521996/i.i.-.20230904-144446.txt)

**Comment by jzhansen** [comment]
Hi Alex,

I left a msg on your personal e-mail about some fast formulas for Apéry's and Catalan's constants, together with the corresponding config files for y-cruncher.  Take a look [here](https://mathoverflow.net/questions/424055/catalans-constant-fast-convergent-series) 

Have a nice time.

Jorge

**Pull request merged**
